services:
  multipurpose_gpt:
    init: true
    image: ghcr.io/pranavnbapat/multipurpose_gpt:latest
    container_name: multipurpose_gpt
    build: .
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/healthz || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
